### ISSUE TITLE
Add an option to package the project.

### ISSUE THREAD

**Issue by Agoldstein1** [ruidfigueiredo/MemorizeADeck#39]
Hi, 

I created my project based on the architecture of the MemorizeADeck project.
@ruidfigueiredo Can you please add the option to package the project and build EXE file? or guide me how to do it..
now as I checked in the package.json of the Electron part - there is no packaging command.

thanks!

**Comment by ruidfigueiredo** [comment]
Electron's documentation on how to package applications is here: https://www.electronjs.org/docs/latest/tutorial/application-distribution

Good luck

**Comment by Agoldstein1** [comment]
I worked on a clean code of the memorize-a-deck project:
I added to memorize-a-deck-electron -> package.json the module: electron-packager
and add a script:
	"package-win": "electron-packager . electron  --overwrite --asar --platform=win32 --arch=ia32  --prune=true --out=buildsep --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"MarkDown\"".

when I run it an EXE file is created but displays a blank file without any error in the console.
What could be the issue?

thanks!

**Comment by ruidfigueiredo** [comment]
The location of the files is important. You have to make sure that the path to the .net project in the connection builder will be the correct one after the project is packaged.

**Comment by Agoldstein1** [comment]
I really change the connection.js code to point the correct location and also print the connection to log and I see the connection success, 
but still, I get a blank page when running the EXE file...

**Comment by Agoldstein1** [comment]
Another question - 
@ruidfigueiredo - I see you split the project into angular level and electron level, they are located in separate projects,
Most of the examples I've seen have combined them together.
What are the benefits of splitting?

thanks
